apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: terraform-platform-config
  labels:
    app.kubernetes.io/name: terraform-platform
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: terraform-platform-data
  labels:
    app.kubernetes.io/name: terraform-platform
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
