apiVersion: v1
kind: Service
metadata:
  name: terraform-platform
  labels:
    app.kubernetes.io/name: terraform-platform
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: terraform-platform
  ports:
    - name: http
      port: 80
      targetPort: http
